### ISSUE TITLE
Compile error (uint8_t, BitOrder, char Value and ...)

### ISSUE THREAD

**Issue by Reza-Abdinezhad** [adafruit/RadioHead#34]
Hi, 

I compiled first of all and I got this error at first:

![Arduino_Compile_Error](https://user-images.githubusercontent.com/4712094/61990021-aba1f880-b04d-11e9-8321-8ec880e6e1f0.PNG)

Then after comment unnecessary lines, I got this error:
![Arduino_Compile_Error2](https://user-images.githubusercontent.com/4712094/61990066-629e7400-b04e-11e9-8062-74efbaef2ff3.PNG)

**So, What should I do?**

**Comment by ladyada** [comment]
STM32 not supported

**Comment by Reza-Abdinezhad** [comment]
OMG,

How about **"Maple Board"**? Is there any difference?

_

> Its good to mention that which board are supported, many thanks.

_
