### ISSUE TITLE
Security of Lora Mesh Network

### ISSUE THREAD

**Issue by mightChamp** [adafruit/RadioHead#56]
Hello,

I want to know about data security in Lora Mesh Network, is it encrypted?
And How can I used two or more different Lora Mesh network at same place, like zigbee ?

Thank You

**Comment by IoTPanic** [comment]
Hey mightChamp,

The security with RadioHead is AES128 if I am not mistaken, but it is in ECB mode which is generally considered insecure for a number of reasons but takes time and skill to defeat and will protect against most trying to tamper or listen in. You can operate two RadioHead networks at a time by putting them on different frequencies, which if you use other solutions is like using another channel.

Notice that I am putting focus on "RadioHead", RadioHead is just a library to use the LoRa radios that is easy for hobbyist to use, and does not cover all of the subject "LoRa Mesh Networks".
